### ISSUE TITLE
Possible to increase the overlay dimensions?

### ISSUE THREAD

**Issue by rpc180** [ericytsang/app.android.screenfilter#1]
Trying to use this on a Android screen that is 1280x480 (car computer) and the current overlay resolution doesn't cover the left and right side.  Would it be possible to resize the overlay so it can accommodate this resolution too (maybe even a bit larger on all sides just in case)?
![20191119_004157](https://user-images.githubusercontent.com/43550213/69119720-73438180-0a65-11ea-9ade-9bdc8edceb40.jpg)

**Comment by ericytsang** [comment]
fixed in version 1.8.9! Thanks for reporting this @rpc180
