### ISSUE TITLE
F-Droid Inclusion?

### ISSUE THREAD

**Issue by TPS** [ericytsang/app.android.screenfilter#3]
@ericytsang Would you support an [RFP](https://gitlab.com/fdroid/rfp) @ [F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-1)?  [IfF](https://en.m.wikipedia.org/wiki/Iff) so, [I'd happily open 1 up](https://gitlab.com/fdroid/rfp/issues/new).

**Comment by phanirithvij** [comment]
I think it is not open source? this seems like a place to gather issues/feedback?
